language: node_js
os:
  - linux
cache:
  yarn: true

stages:
  - name: deploy
    if: type = push AND branch = dev
  - name: PR review
    if: type = pull_request

jobs:
  include:
    - stage: PR review
      env:
        - PR_DEMO_REPO: github.com/trendmicro-frontend/styled-ui-demo.git
        - PR_DEMO_SITE: https://trendmicro-frontend.github.io/styled-ui-demo
        - secure: "vO8p3O2LU1TpRglxCobHwEQAKpOL+BIrjHwntqawaEBK9dLlFG7AK+Nyg/6pw6WXT+tisZwQrdzsg/EBLRarNHDa0h2oIDQA/3MQRGIpMdFg5zezPaJFK25A9+/XYtlgr4M4L11vVAjxQcPzz9FASz4eUuJZ5pmqEI8dr5eL6hfwka5fnyWjNXvLOczjbTQY/93f7Ai1kreAE/puSJMhxJsbc+FJrWskxTnz8EIcT3TB6r+eKg/OpxMegC1Zj0m0zn4Q2SXt+PNqoeIbCt2q7+F6lZJfCH8NFOuFCAmqz3t9l0GiXSEP05ZRAywouFn2c2o5mtsMpuBYdFz2lGprjOiR0C2qzL+PcwPY1aiu4D9IStR2QdNir8m71vVIXJ+OZDTdnOs4X0yoNH5YjqV2YEwkhQcCqVCKYyIH0OMx26KH4+Hp7z+tmbG/HF32k6IsP99F91QgE4KDSqITo82M+G3o308vB1A462+Pl3a29nkC/7ufLA0Kx4fDHW5vjKyAbLLn5/7TuQK6T2yC5l3pOdXbPB3807qYgWV+F2rAWwZHwXvVeYO4tnh+3Nlg5wNwG4gzn5CJWnXmZsj21WkIjTgTSdu/1XGFiUQrWcpEuzWkmzDxb/WRTFVwnyQf7pauNndL/NFACgJsS2BvaxH6wPwB1LLQzZ//mQ1QCVIVQlg="
      node_js:
        - '10'
      before_install:
        - npm install -g yarn
      install:
        - yarn global add octokit-cli
        - yarn install
        - yarn test
        - yarn list --silent react react-dom
      before_script:
        - echo "TRAVIS_COMMIT=${TRAVIS_COMMIT}"
        - echo "TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}"
        - echo "TRAVIS_PULL_REQUEST_SHA=${TRAVIS_PULL_REQUEST_SHA}"
        - PULL_REQUEST_COMMIT=${TRAVIS_PULL_REQUEST_SHA:-$TRAVIS_COMMIT}
        - echo "PUBLIC_URL=/styled-ui-demo/pr-${TRAVIS_PULL_REQUEST}" > ./packages/styled-docs/.env.production
      script:
        - yarn build
        - yarn pre-push
      after_success:
        - git clone "https://${GH_TOKEN}@${PR_DEMO_REPO}" styled-ui-demo > /dev/null 2>&1
        - cd styled-ui-demo
        - git checkout gh-pages
        - git pull "https://${GH_TOKEN}@${PR_DEMO_REPO}" gh-pages > /dev/null 2>&1
        - git rm -rf pr-${TRAVIS_PULL_REQUEST}
        - mkdir -p pr-${TRAVIS_PULL_REQUEST}
        - cp -af ../packages/styled-docs/docs/** pr-${TRAVIS_PULL_REQUEST}/
        - git add pr-${TRAVIS_PULL_REQUEST}
        - git commit -m "added pr-${TRAVIS_PULL_REQUEST}"
        - git push "https://${GH_TOKEN}@${PR_DEMO_REPO}" gh-pages > /dev/null 2>&1
        - cd ..
        - >
          octokit issues create-comment
            --body "Successfully deployed ${PULL_REQUEST_COMMIT} to ${PR_DEMO_SITE}/pr-${TRAVIS_PULL_REQUEST}"
            --owner trendmicro-frontend
            --repo styled-ui
            --issue_number ${TRAVIS_PULL_REQUEST}
    - stage: deploy
      node_js:
        - '10'
      before_install:
        - npm install -g yarn
      install:
        - yarn install
        - yarn test
        - yarn list --silent react react-dom
      script:
        - yarn build
        - yarn pre-push
      after_success: true
      deploy:
        provider: pages:git
        edge: true # dpl v2
        token:
          secure: "EDPLwCPAyG6QGtWRpCmZrs+2t/mX4a0V2ng/ImbhBorpiAfgG9RBMs14454A4qr11xGneeh8khcGZ06egeStBsyzeYc59PGGDHwuhygpOzEgNGLJsldsDJQ0/WmDiAhKQHeUcHO3Ck/2EqILChX3mJBq4zsiuZw5U05AhnXw0RTnLQf0vAAcPKQllZ/pgdbi+nRNZugBpVOc+SoSp9hX+yy01CGXwrWo+MSzgtJl3xrn6k7mZZmyviY0DQE0JMfZsv3kOx1y8JT9F2aXd51aH0rPSBzO8AjWFAhSAenE0mz0sMqDmonDOYGVIHy9jnTBpy9i/E1NuZ4PHM472W2APbuxZA1U3L3e/6ATIx1BQYPGu2uM3DqSbTTtyLZoWXY8rdsA3PQuaeje3XzlQ2fbTSBbN/230GrjtLwKNugvTIRvf3JTaxKn83SUICrrzq0ChDAffNn5AEv7V95Q7ykX1UfDHFs2uhKYDTM9ITeWhPFkm6wDqcqQeu3cxMOLmrMWtwDlLu0VEtIIvZWYEjXxnFYo8E2e34lqn0j1aQEWqpznC+pJ9Rrpajs0dHO3U1dkSWvEli/Z7NmfdQ15MR0J1X/zLbLuPBR+7pT9qRVMC0XU58oky2eEUZ0kDmGAgLLDSynEGxK2JUHcsTBIhXeqaW4rDbT+GOhzGuOgh/sHaBs="
        keep_history: false
        target_branch: gh-pages
        local_dir: "packages/styled-docs/docs"
        on:
          branch: dev
          node: '10'

notifications:
  slack:
    secure: dPF2omw9ykWqJ2C9kV8yq67zJVyezt58kmnRHavrq1+U1e5tDZootxoMjwMzq/T3pctghLbE4QYtg4s3GxINP5mMLMKLoUjDqsnFijKXB9jInWdbxFcDi0pY1w3KimEgSUWd5UZS6WWH23mPGO923KKhu3FE0jnISNlpV6/HQAiAgokMYEMC3Sx9V37iUQsnVBpshhEHMXbK6s9kp6H1gmmfPNuqnSJN0PQ9OaRKlUOlbFjgahFJdljG/TG1qeeGGxUzGu+r1tBmsfsjSqgWbcRDNfHpkx1PeelyhorsA6/CMBW82tVAGA5Z03nw0USrETG8vqPm/B6nnAa+vCvXaUxeft0R75Dczmx9FqGNygyrIwbtxjel5BQCYovVxjkHDniOhd7n0I7c97aXkaaJTvSV2CRSt7DmOPiNE+6mqBaEh9f7OfjsTA8/nShsaVQ5DQAuGfxsSjRTDuJY5NGjBgfIF/2nT2gS1cS/QQza6HcijaOWKTRCgT6/PC++oNTTy6FK1H7epYe41HmIYCDF/Urk1k+DlmCSbshdIGRg05anuTLqCPi6Tz7fFKNNzY4uuB6315vDgKOI91JTIM+5QBCgxjm09E2eIiEpZgIEicvjs1CKZIsfi9R1HgkWD+mngcJvYApwQ+qwvdV/L+zLUkWR9ifz3uFIFtssK30OWQ8=
